[project]
name = "toshu"
version = "0.01"
description = "A python command line todo application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"alembic>=1.14.0",
	"plotext>=5.3.2",
	"pytest>=8.3.4",
	"pyyaml>=6.0.2",
	"sqlalchemy>=2.0.36",
	"termcharts>=1.1.2",
	"typer>=0.15.1",
]
authors = [{ name = "Kartikey Shahi", email = "kartikeyshahi@hotmail.com" }]
license = { file = "LICENSE" }
keywords = ["todo", "cli", "task-manager"]
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
]


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
toshu = "toshu.main:app" # entry point for my CLI app

[tool.setuptools.packages.find]
where = ["."]
exclude = ["migrations", "tests", "migrations.*", "tests.*"]

[tool.ruff]
select = ["E", "F", "I"]

[tool.ruff.isort]
known-first-party = []
known-third-party = []
